(add-to-list 'load-path "~/.emacs.d/personal/modules")
;;(require 'prelude-ensime)
(require 'prelude-scala-sbt)
(require 'prelude-dired)
(require 'prelude-company)
(require 'prelude-compact)
(require 'prelude-themes)
